In [55]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression
import matplotlib.pyplot as plt
import seaborn
seaborn.set()

In [56]:
raw_data = pd.read_csv('F:\\Udemy Courses\\Udemy - Machine Learning\\Learning ML & DS\\Py-Master\\ML\\2_linear_reg_multivariate\\Exercise\\hiring.csv')
raw_data

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0        NaN                    8.0                           9      50000
1        NaN                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    NaN                           7      72000
7     eleven                    7.0                           8      80000

In [57]:
import math
med=math.floor(raw_data['test_score(out of 10)'].median())
# print(med)
raw_data['test_score(out of 10)']=raw_data['test_score(out of 10)'].fillna(med)
# raw_data['test_score(out of 10)'][6]=med
raw_data

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0        NaN                    8.0                           9      50000
1        NaN                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    8.0                           7      72000
7     eleven                    7.0                           8      80000

In [58]:
raw_data.experience=raw_data.experience.fillna('zero')
from word2number import w2n
raw_data.experience=raw_data.experience.apply(w2n.word_to_num)
raw_data

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0           0                    8.0                           9      50000
1           0                    8.0                           6      45000
2           5                    6.0                           7      60000
3           2                   10.0                          10      65000
4           7                    9.0                           6      70000
5           3                    7.0                          10      62000
6          10                    8.0                           7      72000
7          11                    7.0                           8      80000

In [64]:
data=raw_data
x=data[['experience','test_score(out of 10)','interview_score(out of 10)']]
y=data['salary($)']
reg=LinearRegression()
reg.fit(x,y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [67]:
print('Coeff: ',reg.coef_)
print('Intercept: ',reg.intercept_)

Coeff:  [2812.95487627 1845.70596798 2205.24017467]
Intercept:  17737.26346433771


In [68]:
reg.predict([[0,8,9]])

array([52350.0727802])

In [69]:
reg.predict([[10,8,7]])

array([76069.1411936])

In [70]:
reg.predict([[7,9,6]])

array([67270.74235808])